### ISSUE TITLE
ERROR: Could not connect. SQLSTATE[HY000] [1049] Unknown database 'pagan'

### ISSUE THREAD

**Issue by himalimehta** [davidmelhart/PAGAN#1]
@davidmelhart hi, I opened MySQL Workbench and created a new schema 'pagan', and copy+pasted the MySQL commands you have provided on github under the source code files. I also changed the names for my local server, user, password, and db name on the config.php file as you suggested.

For reference, I have saved the downloaded PAGAN-master folder containing all the files from github in the following path on my computer: C:\wamp64\www\PAGAN-master 

Once I did all that, I typed http://localhost/login.php in my chrome browser but it wasn't able to connect. I then moved each and every individual file from PAGAN-master folder to the www folder (C:\wamp64\www\), but that doesn't seem to work either. I am now getting the following error: "ERROR: Could not connect. SQLSTATE[HY000] [1049] Unknown database 'pagan' "

Could you please provide a more detailed version of the currently existing directions on how to get the PAGAN annotation tool to work on the browser?

**Comment by davidmelhart** [comment]
@himalimehta Thank you for the feedback, I updated the readme. Your issue seems to be that you don't have a database named `pagan`. First, please create this database then run the SQL commands on it.

If you still cannot connect, you probably set up your `config.php` incorrectly. You might have to create a new user to make sure you have the right info. The server should be `localhost`, the name and password what you picked, and the server `pagan`. Be sure to grant all privileges to the user.

I have tested the system on a blank install on Xampp and it works locally with both YouTube links and uploaded videos. Though there were a few minor bugs :) These have been fixed and the readme updated.
